### ISSUE TITLE
Enhance newcomers UX − Trello auth

### ISSUE THREAD

**Issue by nicoespeon** [nicoespeon/trello-kanban-analysis-tool#43]
When you first come to the hosted app, Trello authentication tries to pop up to request you permissions. Meanwhile, the whole page is blank.

Unfortunately, user may block pop-ups by default. Without any visible information, he may not noticed that a pop-up has been blocked − or may not understand why − and simply leave, thinking it is broken. 

I faced this issue once and I get a feedback on that very issue − someone thinking the app didn't work.

## Todos

- [x] Render default view with a "Connect to Trello" button
- [x] Refactor the app to kick-off `Cycle.run()` from the beginning, calling Trello authentication on button click
- [x] Handle refresh, when user is already connected to Trello − don't ask him to click on the connect button everytime
